### PR TITLE
Fix invalid LinkButtonStyle

### LINKED ISSUE #1759: Invalid link button style in admin settings
**Describe the bug**
Selecting the *warning* link style in the admin settings results in showing the default and not the warning button color.

**Expected behavior**
Show correct button color

### PR DESCRIPTION
**Pull request by samuelwei**
# Fixes #1759 

## Type (Highlight the corresponding type)

- **Bugfix**
- Feature
- Documentation
- Refactoring (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist

- [x] Code updated to current develop branch head
- [x] Passes CI checks
- [x] Is a part of an issue
- [ ] Tests added for the bugfix or newly implemented feature, describe below why if not
- [x] Changelog is updated
- [ ] Documentation of code and features exists

## Changes

- Replace invalid LinkButtonStyle with valid style
- Fix missing translation for help and contrast style

### CODE REVIEW

File: app/Enums/LinkButtonStyle.php [hunk 1]
```diff
@@ -11,9 +11,25 @@ enum LinkButtonStyle: string
...
     case SUCCESS = 'success';
     case DANGER = 'danger';
-    case WARNING = 'warning';
+    case WARN = 'warn';
     case INFO = 'info';
     case HELP = 'help';
     case CONTRAST = 'contrast';
     case LINK = 'link';
+
+    /* WARNING is deprecated, use WARN instead */
```
Comment (Sabr1n4W) [inline app/Enums/LinkButtonStyle.php]: Maybe it would be possible to add `@deprecated` to the warning to improve it.

But I'm not sure if this would really improve the warning or if it could lead to other problems.

**Review by Sabr1n4W — CHANGES_REQUESTED** [review]

File: app/Enums/LinkButtonStyle.php (hunk 1 above)
Comment (samuelwei) [reply app/Enums/LinkButtonStyle.php]: Of course I just forgot the syntax yesterday :)

**Review by Sabr1n4W — APPROVED** [review]
