### PR TITLE
Change admin interface layout

### LINKED ISSUE #97: Buttons overflow in user list
**Describe the bug**

**To Reproduce**
1. Add uers with long names or emails
2. See list of users
3. See buttons overflow the table 

**Expected behavior**
The overflow should be prohibited, eg. shorten long emails and names: firstname.middlename.lastname@subdomain.domain.tld -> firstname.middlename... Using a hover the whole attribute is shown

**Screenshots**
image

### PR DESCRIPTION
**Pull request by SamuelWei**
# Fixes #97

## Type (Highlight the corresponding type)
- Bugfix
- Feature
- Documentation
- **Refactoring** (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist
- [x] Code updated to current masters head
- [x] Passes CI checks
- [x] Is a part of an issue
- [x] Tests added for the bugfix or newly implemented feature, describe below why if not
- [x] Changelog is updated
- [x] Documentation of code and features exists

## Changes

- Implemented new settings menu to use more screen space
- Improve handling of overflowing text in tables -> trucated with tooltip to show full text

### CODE REVIEW

**Comment by SamuelWei** [comment]
### New Settings overview page
Overview of all settings the user has access to and a small description of what this setting can do. Moved settings from the user dropdown to the top-level menu
image
### New settings details page
More space available as the sidebar in gone. With a click on the home button the user gets back to the overview page
image

**Comment by SamuelWei** [comment]
@dennis95stumm What do you think about this design refactoring. Currently it is just a draft, but it could help solve some of the issues of #97

**Comment by dennis95stumm** [comment]
This wouldn't remove the problem with the overflow. Too long text could always lead to the problem. Here we must either shot the text with dots or make the table scrollable in case the table too wide.

**Comment by dennis95stumm** [comment]
A overview page for the settings is not bad. But the settings nav link left to the user name is not a good solution I think. I would either let the link in the dropdown or put him right to the rooms nav link.

File: resources/js/components/TextTruncate.vue [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  beforeDestroy () {
+    window.removeEventListener('resize', this.checkOverflow);
+  },
+
+  methods: {
+    /**
+     * Enable tooltip if text overflows and is truncated
+     */
+    checkOverflow () {
+      this.disabled = this.$refs.overflow.offsetWidth >= this.$refs.overflow.scrollWidth;
```
Comment (dennis95stumm) [inline resources/js/components/TextTruncate.vue:36]: Please add a test that if the text gets truncated the tooltip gets shown on hover!

File: resources/js/mixins/ActionsColumn.js [hunk 2]
```diff
@@ -53,7 +53,7 @@ export default {
      * @property actionColumnDefinition
      */
     actionColumnDefinition () {
-      return { key: 'actions', label: this.$t('app.actions'), sortable: false };
+      return { key: 'actions', label: this.$t('app.actions'), sortable: false, thClass: 'actionColumn' };
```
Comment (dennis95stumm) [inline resources/js/mixins/ActionsColumn.js:56]: I don't know if that is really a great idea. May be it is. But if there more than the standard amount of actions it must be possible to adjust the width for the table.

File: resources/sass/app.scss [hunk 3]
```diff
@@ -152,3 +152,40 @@ body {
...
+
+
+.text-ellipsis {
+    overflow: hidden;
+    text-overflow: ellipsis;
+    white-space: nowrap;
+}
+
+.actionColumn{
+    width: calc(126px + 0.75rem);
```
Comment (dennis95stumm) [inline resources/sass/app.scss:190]: What magic number are this?

Comment (dennis95stumm) [reply resources/sass/app.scss:190]: Could we use a calculation depending on the button widths?

File: resources/js/components/TextTruncate.vue (hunk 1 above)
Comment (dennis95stumm) [reply resources/js/components/TextTruncate.vue:36]: This also doesn't seem to work. If the text does not get truncated the title gets also shown on hover but the title isn't styled.
Bildschirmfoto von 2021-01-20 19-41-28

File: resources/js/views/settings/Settings.vue [hunk 4]
```diff
@@ -1,76 +1,22 @@
 <template>
   <b-container class='mt-3 mb-5'>
     <h2>{{ $t('settings.title') }}</h2>
+    <b-button
```
Comment (dennis95stumm) [inline resources/js/views/settings/Settings.vue:4]: Could we put the home button on the same line with the title?

File: resources/js/views/settings/SettingsHome.vue [hunk 5]
```diff
@@ -1,5 +1,75 @@
...
+    <b-row cols="1" cols-sm="2" cols-md="3" cols-lg="3" align-v="stretch">
+      <can method='viewAny' policy='SettingPolicy'>
+       <b-col class="p-2 h-100">
+          <b-card class="h-100">
+            <router-link class="stretched-link" :to="{ name: 'settings.application' }">
+            <h2 class="text-center text-success"><i class='fas fa-cogs'></i></h2>
+            </router-link>
+            <b-card-title class="text-center text-success">{{ $t('settings.application.title') }}</b-card-title>
+            <b-card-text>
+              {{ $t('settings.application.tileDescription') }}
```
Comment (dennis95stumm) [inline resources/js/views/settings/SettingsHome.vue:15]: The text for the description in English does not exist!

File: resources/js/lang/en/settings.js [hunk 6]
```diff
@@ -1,6 +1,8 @@
 export default {
   title: 'Settings',
-  description: 'Here you can manage the settings of the application.<br>' +
+  homeButton: 'Back to the overview',
+  overview: 'Overview',
+  overviewDescription: 'Here you can manage the settings of the application.<br>' +
```
Comment (dennis95stumm) [inline resources/js/lang/en/settings.js:5]: Could we put the text on one line?

File: resources/js/views/settings/SettingsHome.vue [hunk 7]
```diff
@@ -1,5 +1,75 @@
...
+      </can>
+      <can method='viewAny' policy='UserPolicy'>
+       <b-col class="p-2 h-100">
+          <b-card class="h-100">
+            <router-link class="stretched-link" :to="{ name: 'settings.users' }">
+              <h2 class="text-center text-success"><i class='fas fa-users'></i></h2>
+            </router-link>
+            <b-card-title class="text-center text-success">{{ $t('settings.users.title') }}</b-card-title>
+            <b-card-text>
+              {{ $t('settings.users.tileDescription') }}
```
Comment (dennis95stumm) [inline resources/js/views/settings/SettingsHome.vue:28]: The text for the description in English does not exist!

File: resources/js/views/settings/SettingsHome.vue [hunk 8]
```diff
@@ -1,5 +1,75 @@
...
+      </can>
+      <can method='viewAny' policy='RolePolicy'>
+       <b-col class="p-2 h-100">
+          <b-card class="h-100">
+            <router-link class="stretched-link" :to="{ name: 'settings.roles' }">
+              <h2 class="text-center text-success"><i class='fas fa-user-tag'></i></h2>
+            </router-link>
+            <b-card-title class="text-center text-success">{{ $t('settings.roles.title') }}</b-card-title>
+            <b-card-text>
+              {{ $t('settings.roles.tileDescription') }}
```
Comment (dennis95stumm) [inline resources/js/views/settings/SettingsHome.vue:41]: The text for the description in English does not exist!

File: resources/js/views/settings/SettingsHome.vue [hunk 9]
```diff
@@ -1,5 +1,75 @@
...
+      </can>
+      <can method='viewAny' policy='RoomTypePolicy'>
+       <b-col class="p-2 h-100">
+          <b-card class="h-100">
+            <router-link class="stretched-link" :to="{ name: 'settings.room_types' }">
+              <h2 class="text-center text-success"><i class='fas fa-tags'></i></h2>
+            </router-link>
+            <b-card-title class="text-center text-success">{{ $t('settings.roomTypes.title') }}</b-card-title>
+            <b-card-text>
+              {{ $t('settings.roomTypes.tileDescription') }}
```
Comment (dennis95stumm) [inline resources/js/views/settings/SettingsHome.vue:54]: The text for the description in English does not exist!

File: resources/js/views/settings/SettingsHome.vue [hunk 10]
```diff
@@ -1,5 +1,75 @@
...
+      </can>
+      <can method='viewAny' policy='ServerPolicy'>
+        <b-col class="p-2 h-100">
+          <b-card class="h-100">
+            <router-link class="stretched-link" :to="{ name: 'settings.servers' }">
+              <h2 class="text-center text-success"><i class='fas fa-server'></i></h2>
+            </router-link>
+            <b-card-title class="text-center text-success">{{ $t('settings.servers.title') }}</b-card-title>
+            <b-card-text>
+              {{ $t('settings.servers.tileDescription') }}
```
Comment (dennis95stumm) [inline resources/js/views/settings/SettingsHome.vue:67]: The text for the description in English does not exist!

File: resources/js/views/settings/roles/Index.vue [hunk 11]
```diff
@@ -134,9 +138,9 @@ export default {
   computed: {
     tableFields () {
       const fields = [
-        { key: 'id', label: this.$t('settings.roles.id'), sortable: true },
+        { key: 'id', label: this.$t('settings.roles.id'), sortable: true, tdClass: 'td-max-width-0-lg', thStyle: { width: '8%' } },
         { key: 'name', label: this.$t('settings.roles.name'), sortable: true },
-        { key: 'default', label: this.$t('settings.roles.default'), sortable: true }
+        { key: 'default', label: this.$t('settings.roles.default'), sortable: true, tdClass: 'td-max-width-0-lg', thStyle: { width: '15%' } }
```
Comment (dennis95stumm) [inline resources/js/views/settings/roles/Index.vue:143]: why do you use the `td-max-width-0-lg` when the text truncate is not used in the cell?

File: resources/js/views/settings/roomTypes/Index.vue [hunk 12]
```diff
@@ -233,8 +241,8 @@ export default {
 
     tableFields () {
       const fields = [
-        { key: 'description', label: this.$t('settings.roomTypes.description'), sortable: true },
-        { key: 'short', label: this.$t('settings.roomTypes.icon'), sortable: true }
+        { key: 'description', label: this.$t('settings.roomTypes.description'), sortable: true, tdClass: 'td-max-width-0-lg' },
+        { key: 'short', label: this.$t('settings.roomTypes.icon'), sortable: true, tdClass: 'td-max-width-0-lg', thStyle: { width: '10%' } }
```
Comment (dennis95stumm) [inline resources/js/views/settings/roomTypes/Index.vue:245]: why do you use the `td-max-width-0-lg` when the text truncate is not used in the cell?

File: resources/js/views/settings/servers/Index.vue [hunk 13]
```diff
@@ -186,12 +193,12 @@ export default {
...
       const fields = [
-        { key: 'id', label: this.$t('settings.servers.id'), sortable: true },
-        { key: 'description', label: this.$t('settings.servers.description'), sortable: true },
-        { key: 'status', label: this.$t('settings.servers.status'), sortable: true },
-        { key: 'meeting_count', label: this.$t('settings.servers.meetingCount'), sortable: true },
-        { key: 'participant_count', label: this.$t('settings.servers.participantCount'), sortable: true },
-        { key: 'video_count', label: this.$t('settings.servers.videoCount'), sortable: true }
+        { key: 'id', label: this.$t('settings.servers.id'), sortable: true, tdClass: 'td-max-width-0-lg', thStyle: { width: '8%' } },
+        { key: 'description', label: this.$t('settings.servers.description'), sortable: true, tdClass: 'td-max-width-0-lg' },
+        { key: 'status', label: this.$t('settings.servers.status'), sortable: true, tdClass: 'td-max-width-0-lg', thStyle: { width: '10%' } },
```
Comment (dennis95stumm) [inline resources/js/views/settings/servers/Index.vue:198]: why do you use the `td-max-width-0-lg` when the text truncate is not used in the cellsl?

**Review by dennis95stumm — CHANGES_REQUESTED** [review]

File: resources/sass/app.scss (hunk 3 above)
Comment (SamuelWei) [reply resources/sass/app.scss:190]: 126px is the width of the three action buttons, 0.75rem the inner padding of the table cell

File: resources/js/views/settings/Settings.vue (hunk 4 above)
Comment (SamuelWei) [reply resources/js/views/settings/Settings.vue:4]: Would you prefer left or right of the titel?

File: resources/sass/app.scss (hunk 3 above)
Comment (dennis95stumm) [reply resources/sass/app.scss:190]: Could we put this in variables?

File: resources/js/views/settings/Settings.vue (hunk 4 above)
Comment (dennis95stumm) [reply resources/js/views/settings/Settings.vue:4]: I would prefer left of the title!

File: resources/js/mixins/ActionsColumn.js (hunk 2 above)
Comment (SamuelWei) [reply resources/js/mixins/ActionsColumn.js:56]: I changed it to be a data attribute, that can be overwritten by the view

File: resources/js/components/TextTruncate.vue (hunk 1 above)
Comment (SamuelWei) [reply resources/js/components/TextTruncate.vue:36]: I fixed the bug, but don't know how to implement a test for it. I tried but the element width is always 0, so the tooltip is never shown.

Comment (dennis95stumm) [reply resources/js/components/TextTruncate.vue:36]: What about a fixed width and max-widht: 0?

File: resources/js/views/settings/SettingsHome.vue [hunk 14]
```diff
@@ -1,5 +1,75 @@
 <template>
-  <div v-html="$t('settings.description')">
+  <div>
+    <h3>{{ $t('settings.overview') }}</h3>
+    <p>{{ $t('settings.overviewDescription') }}</p>
+    <hr>
+    <b-row cols="1" cols-sm="2" cols-md="3" cols-lg="3" align-v="stretch">
+      <can method='viewAny' policy='SettingPolicy'>
```
Comment (dennis95stumm) [inline resources/js/views/settings/SettingsHome.vue:7]: The Can-Component isn't imported so that the cards displayed even if the user hasn't the necessary permissions.

**Review by dennis95stumm — CHANGES_REQUESTED** [review]

File: resources/js/components/TextTruncate.vue (hunk 1 above)
Comment (SamuelWei) [reply resources/js/components/TextTruncate.vue:36]: Apparently we can't simulate it with real css properties, see https://github.com/jsdom/jsdom#unimplemented-parts-of-the-web-platform. I now mocked the properties for the test
