### PR TITLE
Fix recording access not working in restrictive browsers

### LINKED ISSUE #2851: Recording access not working in restrictive browsers
**Describe the bug**

Currently, room recordings are listed and when clicked, an async function is triggered to generate a link to access the recording. This is a problem as some browsers block the opening of a new window that is not directly caused by a user action.

**To Reproduce**

1. Go to an existing recording using Google Chrome
2. Change network settings in chrome dev tools to have a high latency
3. Click on a recording format

**Expected behavior**
Accessing recordings is independent of the latency or browser pop-up restrictions

**Additional context**
Some issue existed with downloading room files. Issue was fixed in #2726

### PR DESCRIPTION
**Pull request by Sabr1n4W**
# Fixes \#2851

## Type

- **Bugfix**
- Feature
- Documentation
- **Refactoring** (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist

- [x] Code updated to current develop branch head
- [x] Passes CI checks
- [x] Is a part of an issue
- [x] Tests added for the bugfix or newly implemented feature, describe below why if not
- [x] Changelog is updated
- [x] Documentation of code and features exists

## Changes

- Move the access recording route from api to web and redirect directly instead of returning a URL

## Summary by CodeRabbit

* **New Features**
  * Recording viewers now use cross-window messaging and direct link navigation for formats, improving how viewers open in new tabs and surface errors.
  * 404 error page signals file-not-found to the opener window for better UX when viewing recordings.

* **Bug Fixes**
  * Addressed issues with browsers blocking recording access when opening new windows without user interaction.

* **Security**
  * Added Cross-Origin-Opener-Policy header to strengthen cross-window isolation.

### CODE REVIEW

File: resources/js/components/RoomTabRecordingsViewButton.vue [hunk 1]
```diff
@@ -40,43 +38,32 @@
...
+        v-for="format in formats.filter(
+          (format) => !(format.disabled && hideDisabledFormats),
+        )"
+        :key="format.format"
+        icon="fa-solid fa-play"
+        :label="$t('rooms.recordings.format_types.' + format.format)"
+        :data-test="format.format + '-button'"
+        target="_blank"
+        rel="opener"
+        :href="viewFormatUrl(format)"
```
[the remark this answers is not in the document]
Comment (Sabr1n4W) [reply resources/js/components/RoomTabRecordingsViewButton.vue:59]: Added security header (Cross-Origin-Opener-Policy "same-origin") to prevent this.
rel="opener" is needed for the error handling

File: docker/app/nginx/snippets/security-header.conf [hunk 2]
```diff
@@ -13,3 +13,7 @@ add_header Referrer-Policy "strict-origin-when-cross-origin" always;
 # Disable XSS protection
 # See: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-xss-protection
 add_header X-XSS-Protection "0" always;
+
+# Prevent cross-origin window.opener access (COOP)
+# See: https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#cross-origin-opener-policy-coop
+add_header Cross-Origin-Opener-Policy "same-origin" always;
```
[the remark this answers is not in the document]
Comment (Sabr1n4W) [reply docker/app/nginx/snippets/security-header.conf:19]: error handling with window.opener.postMessage() not used for cross origin

File: resources/js/components/RoomTabRecordingsViewButton.vue [hunk 3]
```diff
@@ -117,84 +106,31 @@ const props = defineProps({
...
-          EventBus.emit(EVENT_FORBIDDEN);
-          return;
-        }
+  if (props.roomAuthToken) {
+    url +=
+      "?room_auth_token=" +
+      props.roomAuthToken.id +
+      "&room_auth_token_type=" +
+      props.roomAuthToken.type;
+  }
```
[the remark this answers is not in the document]
Comment (Sabr1n4W) [reply resources/js/components/RoomTabRecordingsViewButton.vue:115]: Adjusted this

File: resources/views/errors/404.blade.php [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+@section("title", "Not Found")
+@section("message", "Not Found")
+@section("code", 404)
+
+@push("scripts")
+    <script>
+        if (window.opener) {
+            window.opener.postMessage(
+                {
+                    type: "file_not_found",
```
Comment (samuelwei) [inline resources/views/errors/404.blade.php]: Can we do a more general type here?

File: resources/js/components/RoomTabRecordingsViewButton.vue [hunk 5]
```diff
@@ -117,84 +106,29 @@ const props = defineProps({
...
-function downloadFormat(format) {
-  isLoadingAction.value = true;
+  const roomHref = router.resolve({
+    name: "rooms.view",
+    params: { id: props.roomId },
+  }).href;
 
-  // Update value for the setting and the effected file
-  const config = {};
+  const url = new URL(
```
Comment (samuelwei) [inline resources/js/components/RoomTabRecordingsViewButton.vue]: Move logic to backend: app/Http/Resources/RecordingFormatResource.php

File: resources/js/components/RoomTabRecordings.vue [hunk 6]
```diff
@@ -444,10 +452,45 @@ function onPage(event) {
...
 onRoomHasChanged(
   () => props.room,
   () => loadData(),
 );
+
+function handleRecordingErrorMessages(event) {
+  // Check origin
+  if (event.origin !== settingsStore.getSetting("general.base_url")) return;
+  if (event.data?.type === null || event.data?.type === undefined) return;
+  if (event.data.type === HTTP_FILE_NOT_FOUND) {
```
Comment (samuelwei) [inline resources/js/components/RoomTabRecordings.vue]: Add second case for general HTTP_NOT_FOUND

File: resources/js/components/RoomTabFiles.vue [hunk 7]
```diff
@@ -444,7 +444,7 @@ function handleFileErrorMessages(event) {
   // Check origin
   if (event.origin !== settingsStore.getSetting("general.base_url")) return;
   if (event.data?.type === null || event.data?.type === undefined) return;
-  if (event.data.type === HTTP_ROOM_FILE_NOT_FOUND) {
+  if (event.data.type === HTTP_FILE_NOT_FOUND) {
```
Comment (samuelwei) [inline resources/js/components/RoomTabFiles.vue]: Add second case for general HTTP_NOT_FOUND

File: resources/js/constants/httpCustomErrorMessages.js [hunk 8]
```diff
@@ -3,7 +3,7 @@ export const HTTP_ROOM_INVALID_CODE = "invalid_code";
...
 export const HTTP_ROOM_INVALID_PERSONALIZED_LINK = "invalid_personalized_link";
 
-export const HTTP_ROOM_GUESTS_NOT_ALLOWED = "guests_not_allowed";
-export const HTTP_ROOM_GUESTS_ONLY = "guests_only";
-export const HTTP_ROOM_FILE_FORBIDDEN = "forbidden";
-export const HTTP_ROOM_FILE_NOT_FOUND = "file_not_found";
+export const HTTP_GUESTS_NOT_ALLOWED = "guests_not_allowed";
+export const HTTP_GUESTS_ONLY = "guests_only";
+export const HTTP_FORBIDDEN = "forbidden";
+export const HTTP_FILE_NOT_FOUND = "file_not_found";
```
Comment (samuelwei) [inline resources/js/constants/httpCustomErrorMessages.js:9]: Add second case for general HTTP_NOT_FOUND

File: resources/views/errors/404.blade.php (hunk 4 above)
Comment (samuelwei) [reply resources/views/errors/404.blade.php]: Use php enum here instead of string

File: app/Enums/CustomErrorMessages.php [hunk 9]
```diff
@@ -11,8 +11,8 @@ enum CustomErrorMessages: string
...
     case ROOM_REQUIRE_CODE = 'require_code';
     case ROOM_INVALID_PERSONALIZED_LINK = 'invalid_personalized_link';
-    case ROOM_GUESTS_NOT_ALLOWED = 'guests_not_allowed';
-    case ROOM_GUESTS_ONLY = 'guests_only';
-    case ROOM_FILE_FORBIDDEN = 'forbidden';
-    case ROOM_FILE_NOT_FOUND = 'file_not_found';
+    case GUESTS_NOT_ALLOWED = 'guests_not_allowed';
+    case GUESTS_ONLY = 'guests_only';
+    case FORBIDDEN = 'forbidden';
+    case FILE_NOT_FOUND = 'file_not_found';
```
Comment (samuelwei) [inline app/Enums/CustomErrorMessages.php:17]: Add second case for general HTTP_NOT_FOUND

**Review by samuelwei — CHANGES_REQUESTED** [review]

File: resources/js/components/RoomTabRecordingsEditButton.vue
Comment (samuelwei) [inline resources/js/components/RoomTabRecordingsEditButton.vue]: wouldn't it be better to map the data here instead of L.201? The backend only needs `id` and `disabled`, **not** `format` for each format

**Review by samuelwei — APPROVED** [review]
