### PR TITLE
Error handling room view

### LINKED ISSUE #131: Error handling for click on room
**Describe the bug**
On the user's room overview page, all rooms are displayed as tiles. The user can click on a tile to open the room. If a server error occurs during loading, the error is not reported correctly.

**Expected behavior**
The error should be handled by the global error handler.

### PR DESCRIPTION
**Pull request by SamuelWei**
# Fixes #131 

## Type (Highlight the corresponding type)
- **Bugfix**
- Feature
- Documentation
- Refactoring (e.g. Style updates, Test implementation, etc.)
- Other (please describe):

## Checklist
- [x] Code updated to current masters head
- [x] Passes CI checks
- [x] Is a part of an issue
- [x] Tests added for the bugfix or newly implemented feature, describe below why if not
- [x] Changelog is updated
- [x] Documentation of code and features exists

## Changes

- Fix broken error handler
- Add 503 error to error handler for laravel maintenance mode

### CODE REVIEW

File: resources/js/api/base.js [hunk 1]
```diff
@@ -48,6 +48,8 @@ export default {
       vm.$router.replace({ name: 'home' });
     } else if (responseStatus === env.HTTP_PAYLOAD_TOO_LARGE) { // 413 => payload to large
       vm.flashMessage.error(vm.$t('app.flash.tooLarge'));
+    } else if (responseStatus === env.HTTP_SERVICE_UNAVAILABLE) { // 503 => maintenance mode
+      window.location.reload();
```
Comment (dennis95stumm) [inline resources/js/api/base.js:52]: Would it be better to delay the reload? Otherwise to many requests would be send.

**Review by dennis95stumm — CHANGES_REQUESTED** [review]

File: resources/js/api/base.js (hunk 1 above)
Comment (dennis95stumm) [reply resources/js/api/base.js:52]: It would be better to have a maintenance page for this case!

Comment (dennis95stumm) [reply resources/js/api/base.js:52]: There is no message just a page reload, this is not intuitive!

Comment (dennis95stumm) [reply resources/js/api/base.js:52]: On other errors that not handled here, the page will be broken, since the room card will have an overlay with a loading indicator!

**Review by dennis95stumm — CHANGES_REQUESTED** [review]
